name: Release a draft release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    strategy:
      matrix:
        os: [
          macos-latest,
          ubuntu-latest,
          windows-latest
        ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build & release Electron app
        shell: bash
        env:
          # macOS Code signing certificates
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # macOS notarization API key
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGN: true
        run: |
          pnpm install
          pnpm build --publish="never"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: ${{ matrix.os }}-artifact
          # Directory containing files to upload
          path: release/**/*